# -----------------------------------------------------------------------------
# R FILE             --Tianfu Yang
# Type:              Functions/Analysis/Visualization
# Subtype/Project:   
# Descriptions:    
# -----------------------------------------------------------------------------
# Contents:
# -----------------------------------------------------------------------------
# To-do
# -----------------------------------------------------------------------------
# Pre-load
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# FUNCTION:     Fimpute_geno_file
#' DESCRIPTION
#' @rdname      Fimpute_geno_file
#' @title       generate FIMPUTE genotype input file
#' @param       genodata  the genotype data as a matrix
#' @param       coding_AA the code for genotype AA in the input file
#' @param       coding_AB the code for genotype AB in the input file
#' @param       coding_BB the code for genotype BB in the input file
#' @param       na_input  the code for genotype missing in the input file
#' @param       chip a vector of integer for the chip value
#' @param       PATH a path for the output
#' @param       title a character vallue for the file name
#' @return      the data to be written into the data file.
# -----------------------------------------------------------------------------
#' @export      
#' @note        a wraper to generate FIMPUTE input genotype file
# @examples    
# -----------------------------------------------------------------------------
Fimpute_geno_file = function(
  genodata,
  coding_AA = "AA", 
  coding_AB = "AB", 
  coding_BB = "BB",
  na_input = NULL,
  chip = NULL,
  PATH    = "",
  title   = "NewImp"
){
  # parameter check
  cat("Re-coding genotypes... \n")
  
  genodata = as.matrix(genodata)
  if (!(is.null(na_input))){
    genodata[genodata == na_input] = NA
  }
  if(is.null(chip)){
    chip = rep("1", nrow(genodata))
  }
  
  if(any(!(genodata %in% c(coding_AA,coding_AB,coding_BB,NA)),na.rm = T)) {
    stop("unexpected value")
  }
  
  genodata_new = genodata
  genodata_new[is.na(genodata)] = 5
  genodata_new[genodata == coding_AA] = 0
  genodata_new[genodata == coding_AB] = 1
  genodata_new[genodata == coding_BB] = 2
  
  cat("Converting genotypes... \n")
  
  geno_string = pbapply(genodata_new, 1, FUN = function(x) paste0(x, collapse = ""))
  file_data = data.frame(ID = rownames(genodata_new),
                         Chip = chip,
                         Call... = geno_string,stringsAsFactors = F)
  file_name = paste0(PATH, title, ".geno")
  write.table(x = file_data, file = file_name,
              quote = FALSE, row.names = FALSE, col.names = TRUE)
  cat("The genotype data has been wroten to", file_name, "\n")
  return(file_data)
}

# -----------------------------------------------------------------------------
# FUNCTION:     Fimpute_map_file
#' DESCRIPTION
#' @rdname      Fimpute_map_file
#' @title       generate FIMPUTE map input file
#' @param       geno_map a geno.map object 
#' @param       chip  not support yet  
#' @param       PATH a path for the output
#' @param       title a character vallue for the file name
#' @return      the data to be written into the data file.
# -----------------------------------------------------------------------------
#' @export      
#' @note        a wraper to generate FIMPUTE input map file
# @examples    \
# -----------------------------------------------------------------------------

Fimpute_map_file  = function(
  geno_map,
  chip   = NULL,         ## not supported yet
  PATH   = "",
  title  = "NewImp"
){
  check_map_order = function(geno_map){
    chr_diff = diff(as.numeric(geno_map$CHR))
    chr_diff_positive = all(chr_diff >= 0)
    
    res_diff = tapply(geno_map$POS, geno_map$CHR, diff)
    all_diff_positive = all(unlist(lapply(res_diff, function(x) all(x >= 0))))
    if(!all_diff_positive | !chr_diff_positive){
      stop("The map has not been correctly ordered.")
    }
  }
  
  #### check
  n_mar = nrow(geno_map)
  if (is.null(chip)){
    chip = 1: n_mar
  }
  check_map_order(geno_map)
  
  #### data
  file_data = data.frame(SNP_ID = geno_map$SNPID, 
                         Chr    = as.numeric(geno_map$CHR), 
                         Pos    = geno_map$POS, 
                         Chip1 = chip)
  
  #### file name
  file_name = paste0(PATH, title, ".map")
  write.table(x = file_data, file = file_name,
              quote = FALSE, row.names = FALSE, col.names = TRUE)
  cat("The map data has been wroten to", file_name, "\n")
  return(file_data)
}

# -----------------------------------------------------------------------------
# FUNCTION:     Fimpute_read_geno
#' DESCRIPTION
#' @rdname      Fimpute_read_geno
#' @title       Read genotype file generated by FImpute
#' @param       imputed_file the genotype file generated by FImpute
#' @param       map_file the map file used by FImpute
#' @param       ex_snp_file the ex_snp file generated by FImpute?
#' @return      a matrix of genotypes (0/1/2 output)
# -----------------------------------------------------------------------------
#' @export      
#' @note        Read genotype file generated by FImpute
# @examples    \
# -----------------------------------------------------------------------------

Fimpute_read_geno = function(
  imputed_file, 
  map_file, 
  ex_snp_file = NULL
){
  ## read data
  cat("## Reading data...\n")
  imputed_geno = fread(imputed_file,
                       colClasses = c("character","character","character"),
                       data.table = FALSE)
  map_geno = read.table(map_file,header = TRUE, as.is = TRUE)
  if (!is.null(ex_snp_file)){
    ex_snp   = scan(file = ex_snp_file, what = "Character", quiet = TRUE)  
  }
  
  ## check geno data
  nmar = nchar(imputed_geno$Calls...[1])
  if(any(nchar(imputed_geno$Calls...) != nmar)){
    stop("the imputed geno has different length.")
  }
  
  ## data split
  cat("## Converting matrix...\n")
  geno_mat_raw = str_split_fixed(imputed_geno$Calls..., "", nmar)
  mode(geno_mat_raw) = "integer"
  
  ## 0/1/2 output
  cat("## Converting Genotypes...\n")
  geno_mat = 5 * (geno_mat_raw >= 5) +
                 (geno_mat_raw == 4) +
                 (geno_mat_raw == 3) +
             2 * (geno_mat_raw == 2) +
                 (geno_mat_raw == 1)
  
  # 0: A1A1            -> 0
  # 1: Unphased heter  -> 1
  # 2: A2A2            -> 2
  # 3: A1A2            -> 1
  # 4: A2A1            -> 1
  
  # 5: missing         -> 5
  # 6: A1–             -> 5
  # 7: A2–             -> 5
  # 8: –A1             -> 5
  # 9: –A2             -> 5
  
  ## MarID and AniID
  cat("## Matching ID info...\n")
  rownames(geno_mat) = imputed_geno$ID
  if (!is.null(ex_snp_file)){
    colnames(geno_mat) = map_geno$SNP_ID[!(map_geno$SNP_ID %in% ex_snp)]
  } else {
    colnames(geno_mat) = map_geno$SNP_ID
  }
  
  return(geno_mat)
}
